### ISSUE TITLE
Pressing F3 causes app crash

### ISSUE THREAD

**Issue by whihathac** [TextAnalysisTool/Releases#11]
![image](https://cloud.githubusercontent.com/assets/7718462/8258711/f9feb7fa-166b-11e5-829b-6f3c8e8e9922.png)

**Comment by DavidAnson** [comment]
Text (searchable) version of exception text:

```
---------------------------
TextAnalysisTool.NET
---------------------------
Sorry, an unhandled exception has occurred and the application is about to terminate!

Please report this problem and include the following details:

TextAnalysisTool.NET, Version=1.0.5616.14348, Culture=neutral, PublicKeyToken=d0f1991e18299f1d - 2015-05-18
System.DivideByZeroException: Attempted to divide by zero.

   at TextAnalysisTool.NET.LineCollection.GetNextMatchingLineNumberInCollection(Int32 number, Filter find, Boolean reverse)

   at TextAnalysisTool.NET.LineCollectionDisplay.FindNextMatch(Filter find, Boolean reverse)

   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)

   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)

   at System.Windows.Forms.ToolStripMenuItem.ProcessCmdKey(Message& m, Keys keyData)

   at System.Windows.Forms.ToolStripManager.ProcessShortcut(Message& m, Keys shortcut)

   at System.Windows.Forms.Form.ProcessCmdKey(Message& msg, Keys keyData)

   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)

   at System.Windows.Forms.Control.PreProcessMessage(Message& msg)

   at System.Windows.Forms.Control.PreProcessControlMessageInternal(Control target, Message& msg)

   at System.Windows.Forms.Application.ThreadContext.PreTranslateMessage(MSG& msg)
---------------------------
OK   
---------------------------
```

**Comment by DavidAnson** [comment]
Brief investigation: The (new) ToolStripMenu* implementation is allowing hotkeys for disabled commands to run if the menu hasn't been opened yet.

**Comment by DavidAnson** [comment]
This bug is fixed in the 2015-06-23 release - thank you for reporting it!

**Comment by wjhssfs** [comment]
Great! I should have tried the layest build before reporting. Thank you!

On Thursday, July 2, 2015, David Anson <notifications@github.com> wrote:

> This bug is fixed in the 2015-06-23 release - thank you for reporting it!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TextAnalysisTool/Releases/issues/11#issuecomment-118084771>
> .
>


-- 
Regards
Jinhui Wu
