### ISSUE TITLE
Bug: App crash when trying to load non-existing filter file from File-> Recent File Filter list 

### ISSUE THREAD

**Issue by whihathac** [TextAnalysisTool/Releases#16]
Text:
---------------------------
TextAnalysisTool.NET
---------------------------
Sorry, an unhandled exception has occurred and the application is about to terminate!

Please report this problem and include the following details:

TextAnalysisTool.NET, Version=1.0.5616.14348, Culture=neutral, PublicKeyToken=d0f1991e18299f1d - 2015-05-18
System.InvalidCastException: Unable to cast object of type 'System.Windows.Forms.ToolStripMenuItem' to type 'System.Windows.Forms.MenuItem'.

   at TextAnalysisTool.NET.MainWindow.FileMenuRecentFilters_Click(Object sender, EventArgs e)

   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)

   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)

   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)

   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)

   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)

   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)

   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)

   at System.Windows.Forms.Control.WndProc(Message& m)

   at System.Windows.Forms.ToolStrip.WndProc(Message& m)

   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)

   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
---------------------------
OK   
---------------------------

**Comment by DavidAnson** [comment]
I'm pretty sure this was fixed in the 2015-06-23 release - could you please try to reproduce it there?
