### ISSUE TITLE
Random crash in TextAnalysisTool

### ISSUE THREAD

**Issue by jbzdarkid** [TextAnalysisTool/Releases#91]
```
---------------------------
TextAnalysisTool.NET
---------------------------
Sorry, an unhandled exception has occurred and the application is about to terminate!

Please report this problem and include the following details:

TextAnalysisTool.NET, Version=1.0.6233.26871, Culture=neutral, PublicKeyToken=d0f1991e18299f1d - 2017-01-24
System.IndexOutOfRangeException: Index was outside the bounds of the array.

   at System.Windows.Forms.Application.ThreadContext.ProcessFilters(MSG& msg, Boolean& modified)

   at System.Windows.Forms.Application.ThreadContext.PreTranslateMessage(MSG& msg)

   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)

   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)

   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)

   at TextAnalysisTool.NET.TextAnalysisTool.Run(String[] args)

   at TextAnalysisTool.NET.TextAnalysisTool.Main(String[] args)
---------------------------
OK   
---------------------------
```

**Comment by vincec-msft** [comment]
That version is over 3 years old. Please try the latest: https://textanalysistool.github.io/
